# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adoption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("신청", "신청"),
                            ("미팅", "미팅"),
                            ("계약서작성", "계약서작성"),
                            ("입양완료", "입양완료"),
                            ("모니터링", "모니터링"),
                            ("취소", "취소"),
                        ],
                        default="신청",
                        help_text="입양 상태",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="메모", null=True)),
                ("monitoring_agreement", models.BooleanField(help_text="모니터링 동의")),
                ("guidelines_agreement", models.BooleanField(help_text="가이드라인 동의")),
                (
                    "meeting_scheduled_at",
                    models.DateTimeField(blank=True, help_text="미팅 일정", null=True),
                ),
                (
                    "contract_sent_at",
                    models.DateTimeField(blank=True, help_text="계약서 전송 시간", null=True),
                ),
                (
                    "adoption_completed_at",
                    models.DateTimeField(blank=True, help_text="입양 완료 시간", null=True),
                ),
                (
                    "monitoring_started_at",
                    models.DateTimeField(blank=True, help_text="모니터링 시작 시간", null=True),
                ),
                (
                    "monitoring_next_check_at",
                    models.DateTimeField(
                        blank=True, help_text="다음 모니터링 확인 시간", null=True
                    ),
                ),
                (
                    "monitoring_end_date",
                    models.DateTimeField(
                        blank=True, help_text="모니터링 종료 예정일", null=True
                    ),
                ),
                (
                    "monitoring_completed_checks",
                    models.IntegerField(default=0, help_text="완료된 모니터링 체크 수"),
                ),
                (
                    "monitoring_total_checks",
                    models.IntegerField(default=0, help_text="총 필요한 모니터링 체크 수"),
                ),
                (
                    "monitoring_status",
                    models.CharField(
                        choices=[
                            ("진행중", "진행중"),
                            ("완료", "완료"),
                            ("지연", "지연"),
                            ("중단", "중단"),
                        ],
                        default="진행중",
                        help_text="모니터링 전반적 상태",
                        max_length=10,
                    ),
                ),
                (
                    "center_notes",
                    models.TextField(blank=True, help_text="센터 메모", null=True),
                ),
            ],
            options={
                "verbose_name": "입양 신청",
                "verbose_name_plural": "입양 신청들",
                "db_table": "adoptions",
            },
        ),
        migrations.CreateModel(
            name="AdoptionContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("contract_content", models.TextField(help_text="실제 계약서 내용")),
                (
                    "guidelines_content",
                    models.TextField(blank=True, help_text="입양 유의사항", null=True),
                ),
                (
                    "user_signature_url",
                    models.CharField(
                        blank=True, help_text="사용자 서명 이미지", max_length=500, null=True
                    ),
                ),
                (
                    "user_signed_at",
                    models.DateTimeField(blank=True, help_text="사용자 서명 시간", null=True),
                ),
                (
                    "center_signature_url",
                    models.CharField(
                        blank=True, help_text="센터 서명 이미지", max_length=500, null=True
                    ),
                ),
                (
                    "center_signed_at",
                    models.DateTimeField(blank=True, help_text="센터 서명 시간", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("대기중", "대기중"),
                            ("사용자서명완료", "사용자서명완료"),
                            ("센터서명완료", "센터서명완료"),
                            ("계약완료", "계약완료"),
                        ],
                        default="대기중",
                        help_text="계약 상태",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "입양 계약서",
                "verbose_name_plural": "입양 계약서들",
                "db_table": "adoption_contracts",
            },
        ),
        migrations.CreateModel(
            name="AdoptionMonitoring",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("post_id", models.CharField(help_text="관련 포스트 ID", max_length=100)),
            ],
            options={
                "verbose_name": "입양 모니터링",
                "verbose_name_plural": "입양 모니터링들",
                "db_table": "adoption_monitoring",
            },
        ),
        migrations.CreateModel(
            name="AdoptionMonitoringCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("check_sequence", models.IntegerField(help_text="체크 순서")),
                ("check_date", models.DateTimeField(help_text="체크 실행 일자")),
                ("expected_check_date", models.DateTimeField(help_text="예정된 체크 일자")),
                ("period_start", models.DateTimeField(help_text="모니터링 대상 기간 시작")),
                ("period_end", models.DateTimeField(help_text="모니터링 대상 기간 종료")),
                (
                    "posts_found",
                    models.IntegerField(default=0, help_text="해당 기간 중 발견된 포스트 수"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("정상", "정상"), ("지연", "지연"), ("미제출", "미제출")],
                        help_text="체크 상태",
                        max_length=10,
                    ),
                ),
                ("delay_days", models.IntegerField(default=0, help_text="지연 일수")),
                (
                    "days_until_deadline",
                    models.IntegerField(blank=True, help_text="마감일까지 남은 일수", null=True),
                ),
                (
                    "next_check_date",
                    models.DateTimeField(blank=True, help_text="다음 체크 예정일", null=True),
                ),
                ("notes", models.TextField(blank=True, help_text="추가 메모", null=True)),
            ],
            options={
                "verbose_name": "모니터링 체크",
                "verbose_name_plural": "모니터링 체크들",
                "db_table": "adoption_monitoring_checks",
                "ordering": ["check_sequence"],
            },
        ),
        migrations.CreateModel(
            name="AdoptionQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("sequence", models.IntegerField(default=0, help_text="질문 순서")),
                ("content", models.TextField(help_text="질문 내용")),
                ("is_active", models.BooleanField(default=True, help_text="활성화 여부")),
            ],
            options={
                "verbose_name": "입양 질문",
                "verbose_name_plural": "입양 질문들",
                "db_table": "adoption_questions",
                "ordering": ["center", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="AdoptionQuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("answer", models.TextField(help_text="응답 내용")),
            ],
            options={
                "verbose_name": "입양 질문 응답",
                "verbose_name_plural": "입양 질문 응답들",
                "db_table": "adoption_question_responses",
            },
        ),
    ]
