# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adoptions", "0001_initial"),
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="animal",
            field=models.ForeignKey(
                help_text="입양 대상 동물",
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.animal",
            ),
        ),
    ]
