# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adoptions", "0002_initial"),
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adoption",
            name="user",
            field=models.ForeignKey(
                help_text="입양 신청자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adoptioncontract",
            name="adoption",
            field=models.ForeignKey(
                help_text="관련 입양 신청",
                on_delete=django.db.models.deletion.CASCADE,
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="adoptioncontract",
            name="template",
            field=models.ForeignKey(
                help_text="사용된 템플릿",
                on_delete=django.db.models.deletion.CASCADE,
                to="centers.adoptioncontracttemplate",
            ),
        ),
        migrations.AddField(
            model_name="adoptionmonitoring",
            name="adoption",
            field=models.ForeignKey(
                help_text="관련 입양 신청",
                on_delete=django.db.models.deletion.CASCADE,
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="adoptionmonitoringcheck",
            name="adoption",
            field=models.ForeignKey(
                help_text="관련 입양 신청",
                on_delete=django.db.models.deletion.CASCADE,
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="adoptionquestion",
            name="center",
            field=models.ForeignKey(
                help_text="관련 센터",
                on_delete=django.db.models.deletion.CASCADE,
                to="centers.center",
            ),
        ),
        migrations.AddField(
            model_name="adoptionquestionresponse",
            name="adoption",
            field=models.ForeignKey(
                help_text="관련 입양 신청",
                on_delete=django.db.models.deletion.CASCADE,
                to="adoptions.adoption",
            ),
        ),
        migrations.AddField(
            model_name="adoptionquestionresponse",
            name="question",
            field=models.ForeignKey(
                help_text="관련 질문",
                on_delete=django.db.models.deletion.CASCADE,
                to="adoptions.adoptionquestion",
            ),
        ),
    ]
