# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("adoption_update", "입양 상태 업데이트"),
                            ("monitoring_reminder", "모니터링 알림"),
                            ("center_update", "센터 정보 업데이트"),
                            ("animal_update", "동물 정보 업데이트"),
                            ("system", "시스템 알림"),
                            ("other", "기타"),
                        ],
                        help_text="알림 타입",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="알림 제목", max_length=200)),
                ("message", models.TextField(help_text="알림 내용")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "낮음"),
                            ("normal", "보통"),
                            ("high", "높음"),
                            ("urgent", "긴급"),
                        ],
                        default="normal",
                        help_text="우선순위",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, help_text="읽음 여부")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, help_text="읽은 시간", null=True),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, help_text="액션 URL", max_length=500, null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, help_text="추가 메타데이터", null=True),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림들",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        help_text="디바이스 타입",
                        max_length=10,
                    ),
                ),
                ("token", models.CharField(help_text="푸시 토큰", max_length=500)),
                (
                    "device_id",
                    models.CharField(
                        blank=True, help_text="디바이스 ID", max_length=200, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="활성화 여부")),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="마지막 사용 시간", null=True),
                ),
            ],
            options={
                "verbose_name": "푸시 토큰",
                "verbose_name_plural": "푸시 토큰들",
                "db_table": "push_tokens",
            },
        ),
    ]
