# Generated by Django 5.0.10 on 2025-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_device_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='platform',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='플랫폼', max_length=10, null=True),
        ),
    ]
