# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "type",
                    models.CharField(
                        choices=[("main", "메인"), ("sub", "서브")],
                        default="main",
                        help_text="배너 타입",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="배너 제목", max_length=200, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="배너 설명", null=True),
                ),
                ("alt", models.CharField(help_text="이미지 대체 텍스트", max_length=200)),
                ("image_url", models.CharField(help_text="R2 이미지 URL", max_length=500)),
                ("order_index", models.IntegerField(default=0, help_text="캐러셀 순서")),
                ("is_active", models.BooleanField(default=True, help_text="활성화 상태")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, help_text="클릭 시 이동할 URL", max_length=500, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "배너",
                "verbose_name_plural": "배너들",
                "db_table": "banners",
                "ordering": ["type", "order_index"],
            },
        ),
    ]
