# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperadminNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("title", models.CharField(help_text="공지사항 제목", max_length=200)),
                ("content", models.TextField(help_text="공지사항 내용")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("system", "시스템"),
                            ("policy", "정책"),
                            ("maintenance", "점검"),
                            ("update", "업데이트"),
                            ("important", "중요"),
                        ],
                        default="system",
                        help_text="공지사항 타입",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True, help_text="공개 여부")),
                ("is_pinned", models.BooleanField(default=False, help_text="상단 고정 여부")),
                (
                    "target_users",
                    models.JSONField(blank=True, help_text="대상 사용자 타입들", null=True),
                ),
                ("view_count", models.IntegerField(default=0, help_text="조회수")),
            ],
            options={
                "verbose_name": "최고관리자 공지사항",
                "verbose_name_plural": "최고관리자 공지사항들",
                "db_table": "superadmin_notices",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("title", models.CharField(help_text="공지사항 제목", max_length=200)),
                ("content", models.TextField(help_text="공지사항 내용")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("general", "일반"),
                            ("important", "중요"),
                            ("urgent", "긴급"),
                            ("event", "이벤트"),
                            ("maintenance", "점검"),
                        ],
                        default="general",
                        help_text="공지사항 타입",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True, help_text="공개 여부")),
                ("is_pinned", models.BooleanField(default=False, help_text="상단 고정 여부")),
                ("view_count", models.IntegerField(default=0, help_text="조회수")),
                (
                    "center",
                    models.ForeignKey(
                        help_text="관련 센터",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항들",
                "db_table": "notices",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
