# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
import django.utils.timezone
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("phone_number", models.CharField(help_text="전화번호", max_length=20)),
                (
                    "verification_code",
                    models.CharField(help_text="인증 코드", max_length=6),
                ),
                ("expires_at", models.DateTimeField(help_text="만료 시간")),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
            ],
            options={
                "verbose_name": "전화번호 인증 요청",
                "verbose_name_plural": "전화번호 인증 요청들",
                "db_table": "phone_verification_requests",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("first_name", models.CharField(editable=False, max_length=150)),
                ("last_name", models.CharField(editable=False, max_length=150)),
                (
                    "username",
                    models.CharField(help_text="아이디", max_length=150, unique=True),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="이메일", max_length=50, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("활성유저", "활성유저"), ("관리자", "관리자"), ("탈퇴유저", "탈퇴유저")],
                        default="활성유저",
                        help_text="회원 유형",
                        max_length=10,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, help_text="닉네임", max_length=100, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="전화번호", max_length=20, null=True
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("일반사용자", "일반사용자"),
                            ("센터관리자", "센터관리자"),
                            ("센터최고관리자", "센터최고관리자"),
                            ("훈련사", "훈련사"),
                        ],
                        default="일반사용자",
                        help_text="사용자 타입",
                        max_length=20,
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, help_text="전화번호 인증 여부"),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(blank=True, help_text="전화번호 인증 시간", null=True),
                ),
                (
                    "kakao_id",
                    models.CharField(
                        blank=True,
                        help_text="카카오 ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, help_text="프로필 이미지 URL", max_length=500, null=True
                    ),
                ),
                (
                    "birth",
                    models.CharField(
                        blank=True,
                        help_text="생년월일 (YYYY-MM-DD)",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="주소", null=True)),
                (
                    "address_is_public",
                    models.BooleanField(default=False, help_text="주소 공개 여부"),
                ),
                (
                    "terms_of_service",
                    models.BooleanField(default=False, help_text="이용약관 동의"),
                ),
                (
                    "privacy_policy_agreement",
                    models.BooleanField(default=False, help_text="개인정보처리방침 동의"),
                ),
                (
                    "terms_agreed_at",
                    models.DateTimeField(blank=True, help_text="약관 동의 시간", null=True),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        help_text="소속 센터",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="centers.center",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_permissions_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
                "db_table": "user",
            },
            managers=[
                ("objects", user.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Jwt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("access", models.TextField(help_text="Access Token")),
                ("refresh", models.TextField(help_text="Refresh Token")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="회원",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT 토큰",
                "verbose_name_plural": "JWT 토큰들",
                "db_table": "jwt_tokens",
            },
        ),
        migrations.CreateModel(
            name="PhoneVerificationToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("phone_number", models.CharField(help_text="전화번호", max_length=20)),
                ("token", models.CharField(help_text="6자리 인증 토큰", max_length=6)),
                ("is_used", models.BooleanField(default=False, help_text="사용 여부")),
                ("expires_at", models.DateTimeField(help_text="만료 시간")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "전화번호 인증 토큰",
                "verbose_name_plural": "전화번호 인증 토큰들",
                "db_table": "phone_verification_tokens",
            },
        ),
    ]
