# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("title", models.CharField(help_text="제목", max_length=200)),
                ("content", models.TextField(help_text="내용")),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("adoption_story", "입양 후기"),
                            ("foster_story", "임시보호 후기"),
                            ("volunteer_story", "봉사 후기"),
                            ("animal_info", "동물 정보"),
                            ("center_info", "센터 정보"),
                            ("general", "일반"),
                        ],
                        default="general",
                        help_text="포스트 타입",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=True, help_text="공개 여부")),
                ("view_count", models.IntegerField(default=0, help_text="조회수")),
                ("like_count", models.IntegerField(default=0, help_text="좋아요 수")),
                ("comment_count", models.IntegerField(default=0, help_text="댓글 수")),
            ],
            options={
                "verbose_name": "포스트",
                "verbose_name_plural": "포스트들",
                "db_table": "posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("image_url", models.CharField(help_text="이미지 URL", max_length=500)),
                ("sequence", models.IntegerField(default=0, help_text="이미지 순서")),
                (
                    "caption",
                    models.CharField(
                        blank=True, help_text="이미지 설명", max_length=200, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "포스트 이미지",
                "verbose_name_plural": "포스트 이미지들",
                "db_table": "post_images",
                "ordering": ["post", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PostTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("tag_name", models.CharField(help_text="태그명", max_length=50)),
            ],
            options={
                "verbose_name": "포스트 태그",
                "verbose_name_plural": "포스트 태그들",
                "db_table": "post_tags",
            },
        ),
    ]
