# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                help_text="작성자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                help_text="관련 포스트",
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="post",
            field=models.ForeignKey(
                help_text="관련 포스트",
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="posttag",
            unique_together={("post", "tag_name")},
        ),
    ]
