# Generated by Django 5.0.1 on 2025-08-22 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_postimage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("name", models.CharField(help_text="태그명", max_length=50, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="태그 설명", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="활성화 여부")),
                ("usage_count", models.IntegerField(default=0, help_text="사용된 횟수")),
            ],
            options={
                "verbose_name": "시스템 태그",
                "verbose_name_plural": "시스템 태그들",
                "db_table": "system_tags",
                "ordering": ["name"],
            },
        ),
    ]
