# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("name", models.CharField(help_text="동물 이름", max_length=100)),
                (
                    "announce_number",
                    models.CharField(
                        blank=True, help_text="공고번호", max_length=50, null=True
                    ),
                ),
                (
                    "breed",
                    models.CharField(
                        blank=True, help_text="품종", max_length=100, null=True
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        blank=True, help_text="나이", max_length=20, null=True
                    ),
                ),
                ("is_female", models.BooleanField(help_text="암컷 여부")),
                (
                    "weight",
                    models.FloatField(blank=True, help_text="체중 (kg)", null=True),
                ),
                ("neutering", models.BooleanField(help_text="중성화 여부")),
                ("vaccination", models.BooleanField(help_text="예방접종 여부")),
                ("heartworm", models.BooleanField(help_text="심장사상충 예방 여부")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("보호중", "보호중"),
                            ("입양대기", "입양대기"),
                            ("입양진행중", "입양진행중"),
                            ("입양완료", "입양완료"),
                            ("안락사", "안락사"),
                            ("자연사", "자연사"),
                            ("반환", "반환"),
                        ],
                        default="보호중",
                        help_text="보호 상태",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="동물 설명", null=True),
                ),
                (
                    "personality",
                    models.TextField(blank=True, help_text="성격", null=True),
                ),
                (
                    "health_notes",
                    models.TextField(blank=True, help_text="건강 상태 메모", null=True),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, help_text="특별한 요구사항", null=True),
                ),
                ("adoption_fee", models.IntegerField(default=0, help_text="입양비")),
                ("is_public", models.BooleanField(default=True, help_text="공개 여부")),
            ],
            options={
                "verbose_name": "동물",
                "verbose_name_plural": "동물들",
                "db_table": "animals",
            },
        ),
        migrations.CreateModel(
            name="AnimalImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("image_url", models.CharField(help_text="이미지 URL", max_length=500)),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="대표 이미지 여부"),
                ),
                ("sequence", models.IntegerField(default=0, help_text="이미지 순서")),
            ],
            options={
                "verbose_name": "동물 이미지",
                "verbose_name_plural": "동물 이미지들",
                "db_table": "animal_images",
                "ordering": ["animal", "sequence"],
            },
        ),
    ]
