# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        ("centers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="center",
            field=models.ForeignKey(
                help_text="보호소/센터",
                on_delete=django.db.models.deletion.CASCADE,
                to="centers.center",
            ),
        ),
        migrations.AddField(
            model_name="animalimage",
            name="animal",
            field=models.ForeignKey(
                help_text="관련 동물",
                on_delete=django.db.models.deletion.CASCADE,
                to="animals.animal",
            ),
        ),
    ]
