# Generated by Django 5.0.1 on 2025-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="heartworm",
            field=models.BooleanField(default=False, help_text="심장사상충 예방 여부"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="is_female",
            field=models.BooleanField(default=False, help_text="암컷 여부"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="neutering",
            field=models.BooleanField(default=False, help_text="중성화 여부"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="vaccination",
            field=models.BooleanField(default=False, help_text="예방접종 여부"),
        ),
    ]
