# Generated by Django 5.0.1 on 2025-08-21 12:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_alter_animal_heartworm_alter_animal_is_female_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="나이 (개월 단위)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="체중 (kg, 최대 999.99kg)",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("999.99")),
                ],
            ),
        ),
    ]
