# Generated by Django 5.0.1 on 2025-08-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0004_alter_animal_age_alter_animal_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="admission_date",
            field=models.DateField(blank=True, help_text="센터 입소일", null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="found_location",
            field=models.CharField(
                blank=True, help_text="발견 장소", max_length=200, null=True
            ),
        ),
    ]
