# Generated by Django 5.0.1 on 2025-08-22 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0005_animal_admission_date_animal_found_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="megaphone_count",
            field=models.PositiveIntegerField(default=0, help_text="확성기(좋아요) 수"),
        ),
        migrations.CreateModel(
            name="AnimalMegaphone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "animal",
                    models.ForeignKey(
                        help_text="동물",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "동물 확성기",
                "verbose_name_plural": "동물 확성기들",
                "db_table": "animal_megaphones",
                "unique_together": {("user", "animal")},
            },
        ),
    ]
