# Generated by Django 5.0.1 on 2025-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_animal_megaphone_count_animalmegaphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="activity_level",
            field=models.PositiveIntegerField(default=0, help_text="활동량 수준"),
        ),
        migrations.AddField(
            model_name="animal",
            name="basic_training",
            field=models.PositiveIntegerField(default=0, help_text="기본 훈련 상태"),
        ),
        migrations.AddField(
            model_name="animal",
            name="sensitivity",
            field=models.PositiveIntegerField(default=0, help_text="예민함 정도"),
        ),
        migrations.AddField(
            model_name="animal",
            name="separation_anxiety",
            field=models.PositiveIntegerField(default=0, help_text="분리불안 정도"),
        ),
        migrations.AddField(
            model_name="animal",
            name="sociability",
            field=models.PositiveIntegerField(default=0, help_text="사회성"),
        ),
        migrations.AddField(
            model_name="animal",
            name="trainer_comment",
            field=models.TextField(blank=True, help_text="훈련사 코멘트", null=True),
        ),
    ]
