# Generated by Django 5.0.10 on 2026-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_adoptionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('incremental', '증분 동기화'), ('full', '전체 동기화'), ('status_check', '상태 체크'), ('status_sync', '상태 동기화')], max_length=20)),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('partial', '부분 성공')], default='success', max_length=20)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('deleted_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '동기화 로그',
                'verbose_name_plural': '동기화 로그들',
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
