# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("animals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
            ],
            options={
                "verbose_name": "센터 찜",
                "verbose_name_plural": "센터 찜들",
                "db_table": "center_favorites",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "content_type",
                    models.CharField(help_text="찜한 콘텐츠 타입", max_length=50),
                ),
                ("content_id", models.CharField(help_text="찜한 콘텐츠 ID", max_length=100)),
            ],
            options={
                "verbose_name": "찜",
                "verbose_name_plural": "찜들",
                "db_table": "favorites",
            },
        ),
        migrations.CreateModel(
            name="PersonalityTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("test_type", models.CharField(help_text="테스트 타입", max_length=50)),
                ("answers", models.JSONField(help_text="테스트 답변들")),
                ("result", models.JSONField(help_text="테스트 결과")),
                (
                    "completed_at",
                    models.DateTimeField(auto_now_add=True, help_text="완료 시간"),
                ),
            ],
            options={
                "verbose_name": "성격 테스트",
                "verbose_name_plural": "성격 테스트들",
                "db_table": "personality_tests",
            },
        ),
        migrations.CreateModel(
            name="AnimalFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "animal",
                    models.ForeignKey(
                        help_text="동물",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "동물 찜",
                "verbose_name_plural": "동물 찜들",
                "db_table": "animal_favorites",
            },
        ),
    ]
