# Generated by Django 5.0.10 on 2025-08-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_personalitytest_result_and_more'),
    ]

    operations = [
    ]
