# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("content", models.TextField(help_text="댓글 내용")),
                ("is_edited", models.BooleanField(default=False, help_text="수정 여부")),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글들",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("content", models.TextField(help_text="답글 내용")),
                ("is_edited", models.BooleanField(default=False, help_text="수정 여부")),
            ],
            options={
                "verbose_name": "답글",
                "verbose_name_plural": "답글들",
                "db_table": "replies",
            },
        ),
    ]
