# Generated by Django 5.0.1 on 2025-08-20 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "버그 신고"),
                            ("feature", "기능 제안"),
                            ("complaint", "불만 사항"),
                            ("praise", "칭찬"),
                            ("other", "기타"),
                        ],
                        help_text="피드백 타입",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="제목", max_length=200)),
                ("content", models.TextField(help_text="내용")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("in_progress", "처리중"),
                            ("resolved", "해결됨"),
                            ("rejected", "거부됨"),
                        ],
                        default="pending",
                        help_text="처리 상태",
                        max_length=20,
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(blank=True, help_text="관리자 답변", null=True),
                ),
                ("priority", models.IntegerField(default=1, help_text="우선순위 (1-5)")),
            ],
            options={
                "verbose_name": "피드백",
                "verbose_name_plural": "피드백들",
                "db_table": "feedback",
            },
        ),
        migrations.CreateModel(
            name="FeedbackStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="고유 식별자",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정일")),
                ("total_feedback", models.IntegerField(default=0, help_text="총 피드백 수")),
                (
                    "resolved_feedback",
                    models.IntegerField(default=0, help_text="해결된 피드백 수"),
                ),
                (
                    "pending_feedback",
                    models.IntegerField(default=0, help_text="대기중인 피드백 수"),
                ),
                (
                    "average_response_time",
                    models.FloatField(default=0.0, help_text="평균 응답 시간 (시간)"),
                ),
            ],
            options={
                "verbose_name": "피드백 통계",
                "verbose_name_plural": "피드백 통계들",
                "db_table": "feedback_stats",
            },
        ),
    ]
