# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                help_text="처리 담당자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                help_text="피드백 작성자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedbackstat",
            name="user",
            field=models.ForeignKey(
                help_text="사용자",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedbackstat",
            unique_together={("user",)},
        ),
    ]
