# Generated by Django 5.0.1 on 2025-08-20 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                help_text="센터 소유자/대표자",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_center",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adoptioncontracttemplate",
            name="center",
            field=models.ForeignKey(
                help_text="관련 센터",
                on_delete=django.db.models.deletion.CASCADE,
                to="centers.center",
            ),
        ),
        migrations.AddField(
            model_name="questionform",
            name="center",
            field=models.ForeignKey(
                help_text="관련 센터",
                on_delete=django.db.models.deletion.CASCADE,
                to="centers.center",
            ),
        ),
    ]
