# Generated by Django 5.0.1 on 2025-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionform",
            name="question_type",
        ),
        migrations.AddField(
            model_name="questionform",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("text", "텍스트"),
                    ("multiple_choice", "다중 선택"),
                    ("single_choice", "단일 선택"),
                    ("checkbox", "체크박스"),
                ],
                help_text="질문 타입",
                max_length=20,
                null=True,
            ),
        ),
    ]
