# Generated by Django 5.0.10 on 2025-10-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_center_has_foster_care_center_has_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='call_available_time',
            field=models.CharField(blank=True, help_text='통화 가능 시간', max_length=200, null=True),
        ),
    ]
